### ISSUE TITLE
publishing the helm chart

### ISSUE THREAD

**Issue by venkatamutyala** [onetimesecret/helm-chart#3]
Hey @onetimesecret where would you prefer we publish the chart? Some type of webserver will be needed to do so. An object store like s3 + cloudfront would work but we are also looking at using github pages. Let us know if you have any preference here.

**Comment by venkatamutyala** [comment]
@onetimesecret any thoughts?

**Comment by mikesindieiev** [comment]
Yes can host it at github pages - https://helm.sh/docs/topics/chart_repository/#github-pages-example

**Comment by venkatamutyala** [comment]
Thanks. Would an OCI artifact for your use case @mikesindieiev ?

**Comment by mikesindieiev** [comment]
Not sure that I get right your question.

According to the helm official docs you can publish helm charts in 2 ways - from **docs/** directory and from c**ustom branch**. They provide a step-by-step guide on how to publish helm chart from **docs/** directory - https://github.com/technosophos/tscharts

**Comment by mikesindieiev** [comment]
No push or pressure here.
Just to sum up all from from the docs above.
So, eventually, to publish the chart on github pages, you need:
1. Create a custom branch with `gh-pages` name
2. Enable GH pages feature
3. Create a `.github/workflows/release.yml` file with the following content:
```yaml
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
With that workflow, every new commit to `main` branch will trigger the release job and with that release job an artifact will be automatically added to the HELM chart hosting page
